# 熵权法
熵权法是一种客观赋值方法。在具体使用的过程中，熵权法根据各指标的变异程度，利用信息熵计算出各指标的熵权，再通过熵权对各指标的权重进行修正，从而得到较为客观的指标权重。

一般来说，若某个指标的信息熵指标权重确定方法之熵权法越小，表明指标值得变异程度越大，提供的信息量越多，在综合评价中所能起到的作用也越大，其权重也就越大。

相反，若某个指标的信息熵指标权重确定方法之熵权法越大，表明指标值得变异程度越小，提供的信息量也越少，在综合评价中所起到的作用也越小，其权重也就越小。

# 1.读取数据

In [2]:
#导入相关库
import copy
import pandas as pd
import numpy as np

In [20]:
data=pd.read_csv('D:\M\python\熵权法\熵权.csv')
data

    抒号  行名      A       B       C      D       E       F      G
0    1  交通  0.343   8.909  20.680  3.521   79.60   4.557  5.002
1    2  中信  0.483  13.270   0.000  1.952  101.50   4.365  5.107
2    3  光大  0.404  13.490  39.010  3.350   78.40   3.615  5.501
3    4  华夏  0.838  17.400   0.000  3.212  138.60   5.918  5.202
4    5  民生  0.838  25.060   8.897  2.868   84.74   4.566  4.907
5    6  广发  0.149   3.132   0.000  3.043   99.19   4.923  3.501
6    7  深发  1.210  30.950  25.290  6.880   93.01   5.643  6.324
7    8  招商  0.593  16.020  13.290  3.041   79.50   4.453  6.591
8    9  兴业  0.637  18.850  12.590  2.984  105.60   4.504  7.227
9   10  浦发  0.898  25.780   9.051  4.238  120.80   4.892  7.534
10  11  烟台  0.190   1.657  13.870  3.938  100.90  11.660  2.557
11  12  蚌埠  0.122   3.880   0.000  6.894   65.45   3.573  4.958

In [25]:
data1=data.iloc[:,2:9]
data1

        A       B       C      D       E       F      G
0   0.343   8.909  20.680  3.521   79.60   4.557  5.002
1   0.483  13.270   0.000  1.952  101.50   4.365  5.107
2   0.404  13.490  39.010  3.350   78.40   3.615  5.501
3   0.838  17.400   0.000  3.212  138.60   5.918  5.202
4   0.838  25.060   8.897  2.868   84.74   4.566  4.907
5   0.149   3.132   0.000  3.043   99.19   4.923  3.501
6   1.210  30.950  25.290  6.880   93.01   5.643  6.324
7   0.593  16.020  13.290  3.041   79.50   4.453  6.591
8   0.637  18.850  12.590  2.984  105.60   4.504  7.227
9   0.898  25.780   9.051  4.238  120.80   4.892  7.534
10  0.190   1.657  13.870  3.938  100.90  11.660  2.557
11  0.122   3.880   0.000  6.894   65.45   3.573  4.958

# 2.指标正向化
   不同的指标代表含义不一样，有的指标越大越好，称为越大越优型指标。有的指标越小越好，称为越小越优型指标，而有些指标在某个点是最好的，称为某点最优型指标。为方便评价，应把所有指标转化成越大越优型指标

## 越小越优型指标：C,D属于此类指标
$$x_{ij}^{'}=max(x_{ij})-x_{ij}$$

In [28]:
#越小越优指标位置,（CD符合）
data2=data1
for i in range(3,5):
    data2.iloc[:,i]=max(data1.iloc[:,i])-data1.iloc[:,i]
data2

        A       B       C      D      E       F      G
0   0.343   8.909  20.680  3.373  59.00   4.557  5.002
1   0.483  13.270   0.000  4.942  37.10   4.365  5.107
2   0.404  13.490  39.010  3.544  60.20   3.615  5.501
3   0.838  17.400   0.000  3.682   0.00   5.918  5.202
4   0.838  25.060   8.897  4.026  53.86   4.566  4.907
5   0.149   3.132   0.000  3.851  39.41   4.923  3.501
6   1.210  30.950  25.290  0.014  45.59   5.643  6.324
7   0.593  16.020  13.290  3.853  59.10   4.453  6.591
8   0.637  18.850  12.590  3.910  33.00   4.504  7.227
9   0.898  25.780   9.051  2.656  17.80   4.892  7.534
10  0.190   1.657  13.870  2.956  37.70  11.660  2.557
11  0.122   3.880   0.000  0.000  73.15   3.573  4.958

## 某点最优型指标：E属于此类指标
设最优点为a, 当a=90时E最优。
$$x_{ij}^{'}=1-\frac{\lvert{x_{ij}-a}\rvert}{max(\lvert{x_{ij}-a}\rvert)}$$

越大越优型指标：其余所有指标属于此类指标
$$x_{ij}^{'}=x_{ij}$$

In [31]:
#某点最优型指标
a=90    #最优型数值
data2.iloc[:,4]=1-abs(data1.iloc[:,4]-a)/max(abs(data1.iloc[:,4]-a))
data2

        A       B       C      D         E       F      G
0   0.343   8.909  20.680  3.373  0.655556   4.557  5.002
1   0.483  13.270   0.000  4.942  0.412222   4.365  5.107
2   0.404  13.490  39.010  3.544  0.668889   3.615  5.501
3   0.838  17.400   0.000  3.682  0.000000   5.918  5.202
4   0.838  25.060   8.897  4.026  0.598444   4.566  4.907
5   0.149   3.132   0.000  3.851  0.437889   4.923  3.501
6   1.210  30.950  25.290  0.014  0.506556   5.643  6.324
7   0.593  16.020  13.290  3.853  0.656667   4.453  6.591
8   0.637  18.850  12.590  3.910  0.366667   4.504  7.227
9   0.898  25.780   9.051  2.656  0.197778   4.892  7.534
10  0.190   1.657  13.870  2.956  0.418889  11.660  2.557
11  0.122   3.880   0.000  0.000  0.812778   3.573  4.958

# 3.数据标准化

In [33]:
#0.002~1区间归一化
[m,n]=data2.shape
data3=copy.deepcopy(data2)
ymin=0.002
ymax=1
for j in range(0,n):
    d_max=max(data2.iloc[:,j])
    d_min=min(data2.iloc[:,j])
    data3.iloc[:,j]=(ymax-ymin)*(data2.iloc[:,j]-d_min)/(d_max-d_min)+ymin
data3

           A         B         C         D         E         F         G
0   0.204719  0.249073  0.531060  0.683152  0.806949  0.123433  0.492277
1   0.333138  0.397650  0.002000  1.000000  0.508163  0.099739  0.513332
2   0.260673  0.405145  1.000000  0.717684  0.823321  0.007183  0.592338
3   0.658772  0.538357  0.002000  0.745552  0.002000  0.291392  0.532382
4   0.658772  0.799330  0.229614  0.815021  0.736823  0.124544  0.473228
5   0.026767  0.052253  0.002000  0.779681  0.539678  0.168601  0.191293
6   1.000000  1.000000  0.648999  0.004827  0.623993  0.257454  0.757368
7   0.434039  0.491341  0.342001  0.780085  0.808313  0.110599  0.810907
8   0.474399  0.587758  0.324092  0.791595  0.452226  0.116893  0.938440
9   0.713809  0.823860  0.233553  0.538359  0.244849  0.164775  1.000000
10  0.064375  0.002000  0.356839  0.598942  0.516349  1.000000  0.002000
11  0.002000  0.077737  0.002000  0.002000  1.000000  0.002000  0.483454

# 4.计算信息熵

In [36]:
#计算信息熵
p=copy.deepcopy(data3)
for j in range(0,n):
    p.iloc[:,j]=data3.iloc[:,j]/sum(data3.iloc[:,j])
print(p)
E=copy.deepcopy(data3.iloc[0,:])
for j in range(0,n):
    E[j]=-1/np.log(m)*sum(p.iloc[:,j]*np.log(p.iloc[:,j]))
E

           A         B         C         D         E         F         G
0   0.042372  0.045916  0.144539  0.091613  0.114256  0.050042  0.072532
1   0.068952  0.073306  0.000544  0.134104  0.071951  0.040436  0.075634
2   0.053953  0.074688  0.272171  0.096244  0.116574  0.002912  0.087275
3   0.136350  0.099245  0.000544  0.099982  0.000283  0.118134  0.078441
4   0.136350  0.147355  0.062494  0.109298  0.104326  0.050492  0.069725
5   0.005540  0.009633  0.000544  0.104558  0.076413  0.068353  0.028185
6   0.206977  0.184349  0.176639  0.000647  0.088351  0.104376  0.111591
7   0.089836  0.090578  0.093083  0.104612  0.114449  0.044838  0.119479
8   0.098190  0.108352  0.088209  0.106156  0.064030  0.047390  0.138270
9   0.147742  0.151878  0.063567  0.072196  0.034668  0.066802  0.147340
10  0.013324  0.000369  0.097121  0.080321  0.073110  0.405414  0.000295
11  0.000414  0.014331  0.000544  0.000268  0.141590  0.000811  0.071232
A    0.869930
B    0.886553
C    0.791352
D    0.923776
E    0.943856
F    0.786842
G    0.937352
Name: 0, dtype: float64

# 5.计算权重

In [37]:
# 计算权重
w=(1-E)/sum(1-E)
w

A    0.151184
B    0.131863
C    0.242518
D    0.088598
E    0.065258
F    0.247760
G    0.072818
Name: 0, dtype: float64

# 6.计算得分

In [38]:
#计算得分
s=np.dot(data3,w)
Score=100*s/max(s)
for i in range(0,len(Score)):
    print(f"第{i}个评价对象得分为：{Score[i]}")

第0个评价对象得分为：61.978905085043124
第1个评价对象得分为：47.814108760598245
第2个评价对象得分为：82.85688884465752
第3个评价对象得分为：57.98535393774951
第4个评价对象得分为：74.31693055597334
第5个评价对象得分为：28.545034579896345
第6个评价对象得分为：100.0
第7个评价对象得分为：70.21578918264656
第8个评价对象得分为：70.73213211688035
第9个评价对象得分为：75.01965061630874
第10个评价对象得分为：71.80409475544857
第11个评价对象得分为：18.679145566011023